package ast.lexer;

public enum TokenType {
    // Single-character tokens.
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,
    COLON, SQUARE_BRACE_LEFT, SQUARE_BRACE_RIGHT, TILDA,
    AND, LOGICAL_AND, PIPE, LOGICAL_OR,

  
    // One or two character tokens.
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
  
    // Literals.
    IDENTIFIER, STRING, NUMBER, FLOAT, INT, DOUBLE, LONG, SHORT, BOOL,

    INCREMENT, DECREMENT,
  
    // Keywords.
    IF, ELSE, ELSE_IF, FOR, DO, WHILE, GOTO, SWITCH, CASE,
    BREAK, STATIC, EXTERN, VOID, CONST, RETURN,

    AUTO,CHAR, CONTINUE, DEFAULT, ENUM, INLINE, SIGNED, SIZEOF, 
    TRUE, FALSE, TYPEDEF, TYPEOF, UNION, UNSIGNED, VOLATILE, 
  
    HASHTAG, INCLUDE, DEFINE,
    PROGRAM, EOF
    //PASS THE STRUCT, DYNAMIC ARRAY, POINTER
  }
